# Generated by Django 5.0.6 on 2024-12-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
